docs_dir: .
site_name: HarpEngine
nav:
  - Home: index.md
  - ...
  - API Reference: api/
theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: amber
      toggle: false
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
plugins:
- awesome-pages
  collapse_single_pages: true