docs_dir: .
site_name: HarpEngine
nav:
  - Home: index.md
theme:
  name: material
  features:
    - toc.integrate
    - navigation.sections
  palette:
    - scheme: slate
      primary: deep-purple
      accent: purple
      toggle: false
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - pymdownx.highlight:
      pygments_lang_class: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.superfences